### ISSUE TITLE
Allow one rule without a rule name as the default or root

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#20]
Instead of having a default of a root rule or having it be specified to the processor, could we have one rule without a rule name that is assumed to be the root?

Such as

~~~
width "Width" : 0..1280
height "Height" : 0..1024

{
     "Image" {
         width, height, "Title" :string,
         "Thumbnail" { width, height, "Url" :uri },
         "IDs" [ *:integer ]
     }
}
~~~

**Comment by codalogic** [comment]
The word "assumed" always worries me!  How about a per-rule directive? 

width "Width" : 0..1280
height "Height" : 0..1024

image-format @(root) {
     "Image" {
         width, height, "Title" :string,
         "Thumbnail" { width, height, "Url" :uri },
         "IDs" [ *:integer ]
     }
}

**Comment by anewton1998** [comment]
You are right. "Assumed" is bad specification language. :)

And a @(root) directive is a good idea. However, for writing unit tests I like the idea of being able to quickly specify things and needing to say "rule x is the root" gets in the way:
~~~
data = do_something()
assert( validate( "[ *[ *:integer] ]", data ) )
~~~

For those situations, there is no need for `root [ * [ *:integer ] ]` or `my_rule @(root) [ * [ * :integer ] ]`

So here's what I'm thinking:
* The grammar supports a nameless rule that MUST be the last rule in the set if it is present. It is not required. If it is present, it the root rule.
* rules may have a @(root) directive. If a rule has that, it is the root rule
* if there is more than one rule that may be considered a root rule, that is an error.

**Comment by anewton1998** [comment]
accidentally closed this issue prematurely

**Comment by codalogic** [comment]
I'd allow the optional unnamed rule to be the first rule. This seems to be the convention in ABNF (https://tools.ietf.org/html/rfc5234) (although I can't see it written anywhere) and Relax NG (http://www.relaxng.org/compact-tutorial-20030326.html).

I'd also allow (@root) to be used to specify more than one root.  A grammar may specify a set of messages that are used in different contexts.  For example, a message request and a message response that may have higher layer semantics (such as HTTP) to tell which is which.

But overall, I think I'm overcoming my concern about the "assumed" nature of an unnamed rule.  Perhaps there can be text along the lines of:

"A single unnamed rule is permitted within a ruleset. If such a rule exists it is taken as the root rule of the grammar unless some external mechanism is used to specify an alternative rule.  One or more root rules may also be specified by annotating such rules using an @(root) per-rule directive."

**Comment by anewton1998** [comment]
I'm fine with first. And your text is excellent.

However while I understand the need for multiple message types, I'm a bit confused about what to do with multiple roots in a rule set. If there are multiple roots, which do I use? If I have to rely on an external mechanism, then there is no need to have a @(root) directive.

**Comment by codalogic** [comment]
I think there are a number of advantages of being able to mark root elements.  It allows a coder to readily see the set of root rules without having to sift through the prose of a document.  "Start here (or here)" is a great help to understanding a grammar.  A validator can try comparing a JSON text against the set of rules marked as root.  Tools my choose to flag an error if it is asked to treat a rule as a root that isn't (unless overridden).  Tools may make special provision for root rules, such as defining constants to identify the different roots etc.

**Comment by anewton1998** [comment]
Ok. I see your point.

**Comment by anewton1998** [comment]
I created a new branch for one nameless rule. Try as I might, I could not get it to work with the rule being on the top, but I could get it to work with it being on the bottom. @codalogic if you wanna take a look...

**Comment by codalogic** [comment]
I couldn't get working what you sent by moving stuff around either.  So I started cutting stuff out to try and find where the problem was.  What I ended up with it:

    rule(:root_rule) { value_rule | array_rule | object_rule }
    rule(:top) { ( spcCmnt | directive ).repeat >> root_rule.maybe >> ( spcCmnt | directive | rule ).repeat }

I'm not sure why this works but the original doesn't.  However, IMO it turns out to be what we really wanted.  A group rule or member rule as a root rule don't really make sense.

However, I would be happy if the root rule could be at top, bottom, or anywhere else.  I don't think we can get the ABNF to enforce this, but that's acceptable to me.  In which case the following is an option:

    rule(:top) { ( spcCmnt | directive | root_rule | rule ).repeat }

**Comment by codalogic** [comment]
OK, the problem was target_rule_name in type_rule accessed via rule_def.  When attempting to allow an unnamed rule at the start, if the first rule was named, the name would actually match target_rule_name, thus consuming the name of the rule.  That left the remainder of the rule to attempt to be consumed by ( spcCmnt | directive | rule ).repeat, which obviously (now!) doesn't work.

So we could have group rule or member rule as top level rules if you wanted them, but I'm still thinking they don't make sense.

My branch is at: https://github.com/codalogic/jcrvalidator/tree/one_nameless_bottom_rule/lib/jcr

I did delete / modify a few tests taking in the above observations to get things passing.

**Comment by anewton1998** [comment]
I grabbed it and merged it.
