### ISSUE TITLE
tbd_type

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#83]
We have `tbd-annotation` and `tbd-directives`. Do we also need `tbd-type` to go in `primitive_def` to indicate the constraints on what can be used to specify future types?

Maybe something along the lines of: `not( '$', '(', '{', '[', ';', ',', '|' )` followed by `*(not-space | q_string)`?

**Comment by anewton1998** [comment]
My only issue with this is that things that would otherwise be syntax errors would now have to be caught by code and not the parser.  For instance, using `int` instead of `integer`. I'm ok with extension points in annotations and directives, but for the types I'm not sure about.

I guess I can get the current Ruby code to catch it and that shouldn't be a big deal. Do you have a PR so I can play with this?

**Comment by codalogic** [comment]
I had a quick play with this and it doesn't look as easy as all that.  The list of special characters to avoid was getting alarmingly long!  Happy to leave it as is for the time being.
